apiVersion: v1
kind: Pod
metadata:
  name: webapi-pod
  namespace: homework
  labels:
    app.kubernetes.io/name: webapi-pod
spec:
  containers:
    - name: webapi
      image: inmyminde/k8s
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm /homework/index.html"]
      ports:
        - name: http-port
          containerPort: 8000
      volumeMounts:
        - name: base-vol
          mountPath: /homework
  initContainers:
    - name: index-html-downloader
      image: busybox:1.28
      volumeMounts:
        - name: base-vol
          mountPath: /init
      command: ["/bin/sh", "-c"]
      args:
        - wget -O /init/index.html https://www.w3schools.com/html/default.asp
  volumes:
    - name: base-vol
      emptyDir: {}

